# Generated by Django 3.2.2 on 2021-05-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='characteristicproduct',
            options={'verbose_name_plural': 'Характеристики товаров'},
        ),
        migrations.AlterModelOptions(
            name='imageproduct',
            options={'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productinshoppingcart',
            options={'verbose_name_plural': 'Товары в корзине'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name_plural': 'Промокод'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='typecharacteristic',
            options={'verbose_name_plural': 'Типы характеристик'},
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(default=None, max_length=10, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Это главное изображение?'),
        ),
    ]
