# Generated by Django 3.2.2 on 2021-05-14 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='sum_without_discount',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Сумма корзины без учета скидки'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
