# Generated by Django 3.2.2 on 2021-05-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210514_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinshoppingcart',
            name='cost_with_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Стоимость с учетом скидки'),
        ),
        migrations.AlterField(
            model_name='productinshoppingcart',
            name='cost_without_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Стоимость без учета скидки'),
        ),
        migrations.AlterField(
            model_name='productinshoppingcart',
            name='final_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='productinshoppingcart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
