# Generated by Django 3.2.2 on 2021-05-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210519_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='final_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='productinshoppingcart',
            name='final_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Общая сумма'),
        ),
    ]
