# Generated by Django 3.2.2 on 2021-05-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210519_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='track_num',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Трек номер'),
        ),
    ]
