# Generated by Django 3.2.2 on 2021-05-26 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_status_statusorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusorder',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.order', verbose_name='Заказ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statusorder',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.status', verbose_name='Статус заказа'),
            preserve_default=False,
        ),
    ]
