# Generated by Django 3.2.2 on 2021-05-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210526_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusorder',
            name='status',
            field=models.CharField(choices=[('НП', 'Не подтвержден'), ('П', 'Принят'), ('О', 'Отправлен'), ('ПК', 'Принят клиентом')], max_length=10, verbose_name='Статус заказа'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
