# Generated by Django 3.2.2 on 2021-05-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210526_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Характеристики'),
        ),
    ]
