# Generated by Django 3.2.2 on 2021-05-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210526_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='main.Category', verbose_name='Категории'),
        ),
    ]
