# Generated by Django 3.2.2 on 2021-05-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='promo_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='track_num',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Трек номер'),
        ),
        migrations.DeleteModel(
            name='CharacteristicProduct',
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
        migrations.DeleteModel(
            name='TypeCharacteristic',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
