# Generated by Django 3.2.2 on 2021-05-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210529_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-pk']},
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='is_added_in_order',
        ),
    ]
